theme: jekyll-theme-hamilton
title: Naufal Rahman Avicena
description: Hi! I am Naufal, an Indonesian studying ecology in China. Most of my work revolves around human-wildlife conflict and AI. My research aim to inform evidence-based human-wildlife conflict mitigation, ensuring that human wellbeing and wildlife conservation are kept at a balance.
